name: sanity

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "**/*.py"
      - .github/workflows/sanity.yml
      - "tests/special_sanity/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read

jobs:
  sanity:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install the current repository
        run: |
          pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cpu
          pip3 install -r requirements.txt
          pip3 install -r requirements-test.txt
          pip3 install --no-deps -e .
      - name: Run sanity test
        run: |
          pytest -s -x tests/special_sanity
      - name: Assert documentation requirement for functions
        run: python3 tests/special_sanity/validate_imported_docs.py
